"""Write a built workspace's own run scripts, next to the workspace.

``cm4eu simplace build`` produces a directory that is complete: the XML, the
project CSV, the linked inputs — and the two scripts that run them. Those
scripts are generated rather than shipped because a run's paths (the container,
the binds, the project file, the line count) are only known once the workspace
exists, and a script that has to be told them again is a script that can be told
them wrongly.

Three properties make the pair worth generating:

**They do not need this package.** ``run_task.sh`` builds the ``singularity``
command line itself from ``run.env``. A retry months later works from a bare
shell, without the conda environment, without ``cm4eu`` installed, and after
this package has moved on — which is the point of putting them in the output
directory rather than in ``submit/``.

**They take the workspace as input.** Both default to their own directory, so
``./submit.sh`` inside the folder is enough, and both accept ``--root`` so a
workspace elsewhere can be driven from anywhere.

**Retry is derived, not remembered.** ``submit.sh --retry`` recomputes what is
outstanding every time it is called, rather than reading a list written when
the array was submitted — such a list goes stale the moment anything is re-run
by hand.

What it derives it from is the one subtle decision here. A task is complete
when **it exited zero**, recorded as a stamp under ``state/``, and *not* when
every one of its cells has an output file: a cell can legitimately produce
nothing. Winter wheat at 63 °N never reaches maturity, so SIMPLACE writes no
yearly file for it, and a coverage-based check would resubmit that task for
ever. The per-cell counts are still reported by ``--status``, where they are
information rather than a trigger.
"""

from __future__ import annotations

import csv
import logging
import stat
from dataclasses import dataclass
from pathlib import Path

from cropmodelling4eu.config import RunConfig
from cropmodelling4eu.simplace.workspace import (
    CONTAINER_DATADIR,
    CONTAINER_OUTDIR,
    CONTAINER_PROJECTDIR,
    CONTAINER_WORKDIR,
    Workspace,
)

logger = logging.getLogger(__name__)

__all__ = ["SlurmResources", "write_run_scripts", "id_column_index"]


@dataclass(slots=True)
class SlurmResources:
    """Defaults baked into the generated ``run.env``, overridable per call."""

    partition: str = "compute"
    cpus: int = 8
    memory: str = "16G"
    time_limit: str = "12:00:00"
    max_concurrent: int = 10

#: Project-CSV columns that hold the cell id, in preference order. SIMPLACE
#: names the output file after this value, so it is what a completed line is
#: recognised by.
_ID_COLUMNS = ("vLocationID", "vLocationId", "location", "vLocation", "projectid")


def id_column_index(project_csv: Path, divider: str = ",") -> int:
    """The 1-based index of the project CSV's cell-id column.

    ``awk`` counts fields from 1, and the retry check needs to pull the id out
    of a line without parsing the whole table, so the index is resolved once
    here and written into ``run.env``.

    Raises
    ------
    KeyError
        If no known id column is present — better than defaulting to column 1
        and silently checking the wrong field against the output filenames.
    """
    with Path(project_csv).open("r", encoding="utf-8", newline="") as handle:
        header = next(csv.reader(handle, delimiter=divider))
    for name in _ID_COLUMNS:
        if name in header:
            return header.index(name) + 1
    raise KeyError(
        f"{Path(project_csv).name} has no cell-id column "
        f"(looked for {', '.join(_ID_COLUMNS)}); its header is {header}"
    )


def _render_env(
    workspace: Workspace,
    config: RunConfig,
    id_column: int,
    resources: SlurmResources,
) -> str:
    """The resolved-values file both scripts source."""
    settings = config.simplace
    # Binds that live inside the run directory are written relative to SP_ROOT
    # so the whole folder can be copied elsewhere and still run; the rest are
    # absolute because they genuinely are.
    external = [f"{workspace.export_dir}:{workspace.export_dir}:ro"]
    if workspace.template_dir is not None:
        external.append(f"{workspace.template_dir}:{workspace.template_dir}:ro")
    if workspace.weather_cache is not None:
        external.append(f"{workspace.weather_cache}:{workspace.weather_cache}:ro")
    external_binds = ",".join(external)
    return f"""\
# =============================================================================
# Resolved settings for this SIMPLACE run. Generated by `cm4eu simplace build`;
# edit freely — nothing regenerates it until the next build, which overwrites.
#
# Sourced by run_task.sh and submit.sh. Every SP_* value may be overridden from
# the environment before either is called, e.g.
#   SP_TIME=24:00:00 ./submit.sh
# =============================================================================

# --- Identity ----------------------------------------------------------------
export SP_RUN_NAME="{config.run_name}"
export SP_CROP="{config.season.crop}"

# --- Paths (absolute; SP_ROOT is overridden by the caller's own location) -----
export SP_ROOT="${{SP_ROOT:-{workspace.root}}}"
export SP_WORK_DIR="${{SP_ROOT}}/workspace"
export SP_OUT_DIR="${{SP_ROOT}}/out"
export SP_LOG_DIR="${{SP_ROOT}}/log"
# One stamp per line range that exited zero. This, not the presence of output
# files, is what --retry goes by: see sp_task_state below.
export SP_STATE_DIR="${{SP_ROOT}}/state"
export SP_PROJECT_CSV="${{SP_WORK_DIR}}/project/{workspace.project_csv.name}"
export SP_EXPORT_DIR="{workspace.export_dir}"

# --- The container and what it sees ------------------------------------------
export SP_IMAGE="${{SP_IMAGE:-{settings.singularity_image}}}"
# The run's own directories are bound relative to SP_ROOT, so copying the whole
# folder elsewhere still runs. The rest are bound at their own absolute paths
# and read-only: the workspace *links* to the export, the template and (when
# the weather is converted) its cache, and a symlink is resolved **inside** the
# container — an unbound target dangles and SIMPLACE fails on a file whose path
# it has just printed.
export SP_BINDS="${{SP_BINDS:-\\
${{SP_WORK_DIR}}:{CONTAINER_WORKDIR},\\
${{SP_OUT_DIR}}:{CONTAINER_OUTDIR},\\
${{SP_ROOT}}/weather:{CONTAINER_DATADIR},\\
${{SP_ROOT}}/projects:{CONTAINER_PROJECTDIR},\\
${{SP_LOG_DIR}}:/simplace/log,\\
{external_binds}}}"
export SP_SOLUTION="{workspace.container_solution}"
export SP_PROJECT="{workspace.container_project}"
export SP_CONTAINER_OUT="{CONTAINER_OUTDIR}"
export SP_LOGLEVEL="${{SP_LOGLEVEL:-ERROR}}"

# --- Work division ------------------------------------------------------------
# The project CSV's lines are the parallelism axis (`simplace run -l=START-END`).
export SP_N_LINES="${{SP_N_LINES:-{workspace.n_lines}}}"
export SP_LINES_PER_TASK="${{SP_LINES_PER_TASK:-{settings.lines_per_task}}}"
# 1-based awk field index of the cell id, used to tell a finished line from an
# unfinished one.
export SP_ID_COLUMN="${{SP_ID_COLUMN:-{id_column}}}"
export SP_DIVIDER="${{SP_DIVIDER:-,}}"

# --- SLURM --------------------------------------------------------------------
export SP_PARTITION="${{SP_PARTITION:-{resources.partition}}}"
export SP_CPUS="${{SP_CPUS:-{resources.cpus}}}"
export SP_MEM="${{SP_MEM:-{resources.memory}}}"
export SP_TIME="${{SP_TIME:-{resources.time_limit}}}"
export SP_MAX_CONCURRENT="${{SP_MAX_CONCURRENT:-{resources.max_concurrent}}}"
# SIMPLACE's own `-l=START-END` runs in one thread of one JVM, so SP_CPUS alone
# buys nothing past the first core. run_task.sh fans a task's own line range
# across this many concurrent singularity/JVM invocations instead -- the same
# pattern SP_MAX_CONCURRENT already uses across array tasks, just within one.
# 1 (default) is unchanged behaviour: one JVM per task.
export SP_CORES_PER_TASK="${{SP_CORES_PER_TASK:-1}}"

# --- Derived ------------------------------------------------------------------
export SP_N_TASKS=$(( (SP_N_LINES + SP_LINES_PER_TASK - 1) / SP_LINES_PER_TASK ))

# First and last (1-based, inclusive) project line of task $1.
sp_task_range() {{
    local task first last
    task="$1"
    first=$(( task * SP_LINES_PER_TASK + 1 ))
    last=$(( first + SP_LINES_PER_TASK - 1 ))
    [ "${{last}}" -gt "${{SP_N_LINES}}" ] && last="${{SP_N_LINES}}"
    echo "${{first}} ${{last}}"
}}

# "<task> <missing> <total>" per task: how many of its cells have no output.
# SIMPLACE names each output after the cell (`<id>_yearly.csv`), so this is
# readable however the run was split and however often it was re-run.
#
# It is a *coverage* measure, not a completion one. A cell can finish with no
# output — winter wheat at 63 N never matures, so no yearly file is written —
# so this is reported, while sp_task_done decides what gets resubmitted.
sp_task_cells() {{
    local done_list
    done_list="$(mktemp)"
    # The sentinel keeps the file non-empty: awk's FNR==NR two-file idiom
    # misreads the *second* file as the first when the first has no records.
    echo "__none__" > "${{done_list}}"
    find "${{SP_OUT_DIR}}" -name '*_yearly.csv' -size +1c -printf '%f\\n' 2>/dev/null \\
        | sed 's/_yearly\\.csv$//' | sort -u >> "${{done_list}}"
    awk -F"${{SP_DIVIDER}}" -v lpt="${{SP_LINES_PER_TASK}}" -v col="${{SP_ID_COLUMN}}" '
        FNR == NR {{ done[$0] = 1; next }}
        FNR == 1  {{ next }}                       # project header
        {{
            line = FNR - 1
            task = int((line - 1) / lpt)
            total[task]++
            id = $col
            gsub(/^[ \\t"]+|[ \\t"\\r]+$/, "", id)
            if (!(id in done)) missing[task]++
        }}
        END {{ for (t = 0; t in total; t++) printf "%d %d %d\\n", t, missing[t] + 0, total[t] }}
    ' "${{done_list}}" "${{SP_PROJECT_CSV}}"
    rm -f "${{done_list}}"
}}

# Has task $1 exited zero? The stamp is named after the *line range*, not the
# task index, so re-splitting the work with a different SP_LINES_PER_TASK
# invalidates the stamps rather than silently reusing them for other lines.
sp_task_done() {{
    # Local, so calling this from inside sp_task_state's loop cannot overwrite
    # the range that loop is about to print.
    local first last
    read -r first last <<<"$(sp_task_range "$1")"
    [ -f "${{SP_STATE_DIR}}/task_${{first}}-${{last}}.done" ]
}}

# "<task> <first> <last> <missing cells> <total cells> <done 0|1>" per task.
sp_task_state() {{
    local task missing total first last done
    sp_task_cells | while read -r task missing total; do
        read -r first last <<<"$(sp_task_range "${{task}}")"
        if sp_task_done "${{task}}"; then done=1; else done=0; fi
        echo "${{task}} ${{first}} ${{last}} ${{missing}} ${{total}} ${{done}}"
    done
}}
"""


#: Runs one line range. Deliberately free of this package: the only things it
#: needs are ``run.env``, ``singularity`` and the image.
_RUN_TASK = r"""#!/bin/bash
# =============================================================================
# Run ONE range of project-file lines through SIMPLACE, in its container.
#
#   ./run_task.sh 3          # task 3 of the array's division
#   ./run_task.sh 4001-6000  # an explicit line range
#   ./run_task.sh            # SLURM array task ${SLURM_ARRAY_TASK_ID}
#
# Options:
#   --root DIR   the built workspace (default: this script's own directory)
#   --dry-run    print the command, run nothing
#   --debug      keep SIMPLACE's own log level
#
# Uses nothing from cropmodelling4eu — everything it needs is in run.env, so a
# retry works from a bare shell long after the build.
# =============================================================================
#SBATCH --job-name=simplace
#SBATCH --ntasks=1
#SBATCH --nodes=1

set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=0
DEBUG=0
RANGE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --root)    SP_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        --debug)   DEBUG=1; shift ;;
        -h|--help) sed -n '2,/^# =\{10,\}$/p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *)         RANGE="$1"; shift ;;
    esac
done

export SP_ROOT="${SP_ROOT:-${SELF_DIR}}"
if [ ! -f "${SP_ROOT}/run.env" ]; then
    echo "ERROR: no run.env under ${SP_ROOT}. Pass --root <built workspace>." >&2
    exit 2
fi
# shellcheck disable=SC1091
source "${SP_ROOT}/run.env"

# A bare number is a task index; anything with a dash is an explicit range.
if [ -z "${RANGE}" ]; then
    RANGE="${SLURM_ARRAY_TASK_ID:-}"
    [ -z "${RANGE}" ] && { echo "ERROR: pass a task index or a LINE-RANGE." >&2; exit 2; }
fi
case "${RANGE}" in
    *-*) FIRST="${RANGE%%-*}"; LAST="${RANGE##*-}" ;;
    *)   read -r FIRST LAST <<<"$(sp_task_range "${RANGE}")" ;;
esac

if [ ! -f "${SP_IMAGE}" ]; then
    echo "ERROR: Singularity image not found: ${SP_IMAGE}" >&2
    echo "       Override with SP_IMAGE=/path/to/image.sif" >&2
    exit 1
fi

mkdir -p "${SP_OUT_DIR}" "${SP_LOG_DIR}" "${SP_STATE_DIR}"
STAMP="${SP_STATE_DIR}/task_${FIRST}-${LAST}.done"
# Cleared up front: a re-run that fails must not leave the previous success
# standing, or --retry would consider the range finished.
rm -f "${STAMP}"

# SIMPLACE's own `-l=START-END` is one thread in one JVM, so a single
# invocation never touches more than one of the task's --cpus-per-task cores.
# SP_CORES_PER_TASK (default 1, unchanged behaviour) splits FIRST-LAST into
# that many contiguous sub-ranges and runs one singularity/JVM per sub-range
# concurrently against the same SP_OUT_DIR/SP_LOG_DIR -- exactly what
# SP_MAX_CONCURRENT already does across array tasks, just within one.
N_WORKERS="${SP_CORES_PER_TASK:-1}"
case "${N_WORKERS}" in ''|*[!0-9]*) N_WORKERS=1 ;; esac
[ "${N_WORKERS}" -lt 1 ] && N_WORKERS=1
TOTAL=$(( LAST - FIRST + 1 ))
CHUNK=$(( (TOTAL + N_WORKERS - 1) / N_WORKERS ))

echo "=================================================="
echo "SIMPLACE ${SP_RUN_NAME}  lines ${FIRST}-${LAST}  (${N_WORKERS} worker(s))"
echo "  node    : $(hostname)"
echo "  job     : ${SLURM_JOB_ID:-none} ${SLURM_ARRAY_TASK_ID:+(task ${SLURM_ARRAY_TASK_ID})}"
echo "  root    : ${SP_ROOT}"
echo "  started : $(date -Is)"
echo "=================================================="

PIDS=()
RANGES=()
cursor="${FIRST}"
while [ "${cursor}" -le "${LAST}" ]; do
    w_first="${cursor}"
    w_last=$(( w_first + CHUNK - 1 ))
    [ "${w_last}" -gt "${LAST}" ] && w_last="${LAST}"
    cursor=$(( w_last + 1 ))

    WCMD=(singularity run -B "${SP_BINDS}" "${SP_IMAGE}"
          /simplace/simplace run
          "-s=${SP_SOLUTION}" "-p=${SP_PROJECT}" "-o=${SP_CONTAINER_OUT}"
          -t=CLUSTER "-l=${w_first}-${w_last}")
    [ "${DEBUG}" -eq 0 ] && WCMD+=("-loglevel=${SP_LOGLEVEL}")
    printf '%q ' "${WCMD[@]}"; echo

    [ "${DRY_RUN}" -eq 1 ] && continue

    "${WCMD[@]}" > "${SP_LOG_DIR}/lines_${w_first}-${w_last}.out" 2>&1 &
    PIDS+=($!)
    RANGES+=("${w_first}-${w_last}")
done

if [ "${DRY_RUN}" -eq 1 ]; then
    echo "--dry-run: nothing executed."
    exit 0
fi

START_S=$(date +%s)
STATUS=0
FAILED=()
for i in "${!PIDS[@]}"; do
    wait "${PIDS[$i]}" || { STATUS=1; FAILED+=("${RANGES[$i]}"); }
done
ELAPSED=$(( $(date +%s) - START_S ))

if [ ${STATUS} -eq 0 ]; then
    date -Is > "${STAMP}"
    echo "OK   lines ${FIRST}-${LAST} in $((ELAPSED / 60))m$((ELAPSED % 60))s"
else
    # No stamp, so the range stays in --retry's set. Per-worker output is
    # under SP_LOG_DIR/lines_<sub-range>.out.
    echo "FAIL lines ${FIRST}-${LAST}: sub-range(s) ${FAILED[*]} exited nonzero" \
         "after $((ELAPSED / 60))m; see ${SP_LOG_DIR}/lines_*.out" >&2
fi
exit ${STATUS}
"""


#: Sizes and submits the array, and recomputes the retry set on demand.
_SUBMIT = r"""#!/bin/bash
# =============================================================================
# Submit this SIMPLACE run as a SLURM array — or re-submit what is missing.
#
#   ./submit.sh                  # the whole run
#   ./submit.sh --status         # what is finished, per task; submits nothing
#   ./submit.sh --retry          # only the tasks that have not exited zero
#   ./submit.sh --lines 1-2000   # one explicit range, as a single job
#   ./submit.sh --local          # run here, in the foreground, no SLURM
#   ./submit.sh --retry --local  # re-run what failed, here, to watch it fail
#   ./submit.sh --dry-run        # print the plan, submit nothing
#
# Options:
#   --root DIR   the built workspace (default: this script's own directory)
#
# Resources come from run.env and can be overridden per call:
#   SP_TIME=24:00:00 SP_MAX_CONCURRENT=40 ./submit.sh --retry
#
# --retry is recomputed every call from the stamps under state/, not from a
# list written when the array was submitted, so it stays correct after any mix
# of array runs, manual re-runs and cancellations. It goes by whether a task
# exited zero rather than by whether every cell has output: a cell that never
# reaches maturity legitimately produces none, and would otherwise be retried
# for ever.
# =============================================================================

set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATUS_ONLY=0
# --retry and --local are independent: what to run, and where to run it. So
# `--retry --local` re-runs the failed ranges here, in the foreground, which is
# the natural way to see why they failed.
RETRY=0
LOCAL=0
DRY_RUN=0
LINES=""

while [ $# -gt 0 ]; do
    case "$1" in
        --root)    SP_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
        --status)  STATUS_ONLY=1; shift ;;
        --retry)   RETRY=1; shift ;;
        --local)   LOCAL=1; shift ;;
        --lines)   LINES="$2"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) sed -n '2,/^# =\{10,\}$/p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *)         echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

export SP_ROOT="${SP_ROOT:-${SELF_DIR}}"
if [ ! -f "${SP_ROOT}/run.env" ]; then
    echo "ERROR: no run.env under ${SP_ROOT}. Pass --root <built workspace>." >&2
    exit 2
fi
# shellcheck disable=SC1091
source "${SP_ROOT}/run.env"
TASK_SCRIPT="${SP_ROOT}/run_task.sh"

echo "=================================================="
echo "SIMPLACE ${SP_RUN_NAME}"
echo "=================================================="
echo "  root         : ${SP_ROOT}"
echo "  project      : ${SP_PROJECT_CSV}"
echo "  lines        : ${SP_N_LINES}  (${SP_LINES_PER_TASK}/task -> ${SP_N_TASKS} tasks)"
echo "  image        : ${SP_IMAGE}"
echo "  outputs      : ${SP_OUT_DIR}"
echo "=================================================="

# --- One explicit range -------------------------------------------------------
if [ -n "${LINES}" ]; then
    [ "${DRY_RUN}" -eq 1 ] && { echo "--dry-run: would run lines ${LINES}"; exit 0; }
    if [ "${LOCAL}" -eq 1 ]; then
        exec "${TASK_SCRIPT}" --root "${SP_ROOT}" "${LINES}"
    fi
    mkdir -p "${SP_LOG_DIR}"
    sbatch --partition="${SP_PARTITION}" --cpus-per-task="${SP_CPUS}" \
        --mem="${SP_MEM}" --time="${SP_TIME}" \
        --output="${SP_LOG_DIR}/sp_%j.out" --error="${SP_LOG_DIR}/sp_%j.err" \
        --export=ALL,SP_ROOT \
        "${TASK_SCRIPT}" "${LINES}"
    exit $?
fi

# --- What is finished ---------------------------------------------------------
# Fields: task, first, last, missing cells, total cells, exited-zero.
STATE="$(sp_task_state)"
PENDING="$(echo "${STATE}" | awk '$6 == 0 { print $1 }' | paste -sd, -)"
N_PENDING=$(echo "${STATE}" | awk '$6 == 0' | wc -l)
N_CELLS_LEFT=$(echo "${STATE}" | awk '{ s += $4 } END { print s + 0 }')
N_CELLS=$(echo "${STATE}" | awk '{ s += $5 } END { print s + 0 }')

echo "  tasks done   : $((SP_N_TASKS - N_PENDING)) / ${SP_N_TASKS}"
echo "  cells with   : $((N_CELLS - N_CELLS_LEFT)) / ${N_CELLS} output"
echo "=================================================="

if [ "${STATUS_ONLY}" -eq 1 ]; then
    echo ""
    echo "task   range           cells    exited 0"
    echo "${STATE}" | while read -r task first last missing total done; do
        [ "${missing}" -eq 0 ] && [ "${done}" -eq 1 ] && continue
        [ "${done}" -eq 1 ] && flag="yes" || flag="NO"
        printf "%-6s %-15s %-8s %s\n" \
            "${task}" "${first}-${last}" "$((total - missing))/${total}" "${flag}"
    done
    echo ""
    echo "Only 'exited 0 = NO' rows are resubmitted by --retry. A task can exit"
    echo "zero with cells missing: SIMPLACE writes no yearly file for a cell that"
    echo "never reaches maturity, which is the expected result far north."
    echo ""
    echo "  ${SP_ROOT}/submit.sh --retry"
    exit 0
fi

# --- Which tasks to run -------------------------------------------------------
if [ "${RETRY}" -eq 1 ]; then
    if [ "${N_PENDING}" -eq 0 ]; then
        echo "Nothing to retry: every task has exited zero."
        exit 0
    fi
    ARRAY="${PENDING}"
else
    ARRAY="0-$((SP_N_TASKS - 1))"
fi

if [ "${LOCAL}" -eq 1 ]; then
    echo "Running ${ARRAY} here, one task at a time."
    [ "${DRY_RUN}" -eq 1 ] && { echo "--dry-run: nothing executed."; exit 0; }
    # Expanded first, then looped over: a `while read` on the far side of a pipe
    # runs in a subshell, so the exit status of a failed task would be lost.
    TASKS=$(for spec in $(echo "${ARRAY}" | tr ',' ' '); do
        case "${spec}" in
            *-*) seq "${spec%%-*}" "${spec##*-}" ;;
            *)   echo "${spec}" ;;
        esac
    done)
    STATUS=0
    for task in ${TASKS}; do
        "${TASK_SCRIPT}" --root "${SP_ROOT}" "${task}" || STATUS=1
    done
    exit ${STATUS}
fi

# --- Submit -------------------------------------------------------------------
# A short lines-per-task silently overruns the cluster's array limit, and sbatch
# then rejects the submission with a message that does not say which number was
# too big.
MAX_ARRAY=$(scontrol show config 2>/dev/null | sed -n 's/^MaxArraySize *= *\([0-9]*\).*/\1/p')
if [ -n "${MAX_ARRAY}" ] && [ "${SP_N_TASKS}" -gt "${MAX_ARRAY}" ]; then
    echo "ERROR: ${SP_N_TASKS} tasks exceeds this cluster's MaxArraySize of ${MAX_ARRAY}." >&2
    echo "       Rebuild with SP_LINES_PER_TASK >=" \
         "$(( (SP_N_LINES + MAX_ARRAY - 1) / MAX_ARRAY ))." >&2
    exit 1
fi

echo "  array        : ${ARRAY}%${SP_MAX_CONCURRENT}"
echo "  resources    : ${SP_PARTITION}, ${SP_CPUS} cpus, ${SP_MEM}, ${SP_TIME}," \
     "${SP_CORES_PER_TASK} core(s)/task"

if [ "${DRY_RUN}" -eq 1 ]; then
    echo "--dry-run: nothing submitted."
    exit 0
fi

mkdir -p "${SP_LOG_DIR}"
JOB=$(sbatch --parsable \
    --partition="${SP_PARTITION}" \
    --cpus-per-task="${SP_CPUS}" \
    --mem="${SP_MEM}" \
    --time="${SP_TIME}" \
    --array="${ARRAY}%${SP_MAX_CONCURRENT}" \
    --output="${SP_LOG_DIR}/sp_%A_%a.out" \
    --error="${SP_LOG_DIR}/sp_%A_%a.err" \
    --export=ALL,SP_ROOT \
    "${TASK_SCRIPT}") || { echo "ERROR: submission failed" >&2; exit 1; }

cat <<EOF

Submitted ${JOB}

  watch    : squeue -u \$USER -j ${JOB}
  logs     : tail -f ${SP_LOG_DIR}/sp_${JOB}_0.out
  progress : ${SP_ROOT}/submit.sh --status
  re-run   : ${SP_ROOT}/submit.sh --retry
  cancel   : scancel ${JOB}
EOF
"""


def _write_executable(path: Path, text: str) -> Path:
    path.write_text(text, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def write_run_scripts(
    workspace: Workspace,
    config: RunConfig,
    resources: SlurmResources | None = None,
    divider: str = ",",
) -> dict[str, Path]:
    """Write ``run.env``, ``run_task.sh`` and ``submit.sh`` into the workspace.

    Returns the three paths, keyed ``env``/``task``/``submit``. Raises
    ``ValueError`` if the workspace carries no project CSV, since the scripts
    would then have no work to divide and no way to tell a finished line from
    an unfinished one.
    """
    if workspace.project_csv is None:
        raise ValueError(
            "workspace.project_csv is unset; build the workspace with "
            "build_workspace() before writing its run scripts"
        )

    id_column = id_column_index(workspace.project_csv, divider)
    paths = {
        name: workspace.root / filename
        for name, filename in (
            ("env", "run.env"), ("task", "run_task.sh"), ("submit", "submit.sh")
        )
    }
    paths["env"].write_text(
        _render_env(workspace, config, id_column, resources or SlurmResources()),
        encoding="utf-8",
    )
    _write_executable(paths["task"], _RUN_TASK)
    _write_executable(paths["submit"], _SUBMIT)

    logger.info(
        "Run scripts written: %s (submit.sh, run_task.sh, run.env; cell id in "
        "project column %d)", workspace.root, id_column,
    )
    return paths
